### ISSUE TITLE
remove class reflection with reified

### ISSUE THREAD

**Issue by RuiMiguel** [mac229/FragmentUtils#1]
modify class reflection in FragmentUtils.kt using reified, :

`fun <T> FragmentManager.findFragmentByTag(fragmentClass: Class<T>, tag: String): T? {
    val fragment = findFragmentByTag(tag)
    return if (fragmentClass.isInstance(fragment)) {
        fragmentClass.cast(fragment)
    } else {
        null
    }
}`
`inline fun <reified T> FragmentManager.findFragmentByTag(tag: String): T? {
    val fragment = findFragmentByTag(tag)
    return if (fragment is T) {
        fragment
    } else {
        null
    }
}`

**Comment by mac229** [comment]
Great suggestion. I've just modified it. Thanks!
